### ISSUE TITLE
XLRDError : ODYM Example and Tutorial 3

### ISSUE THREAD

**Issue by CBreton026** [IndEcol/ODYM#15]
Hi,

I encountered an issue while following the ODYM Example and Tutorial 3 (see below). Apparently, the [xlrd package explicitly dropped support for anything other than xls files](https://stackoverflow.com/questions/65250207/pandas-cannot-open-an-excel-xlsx-file).

For the tutorial, an easy fix was simply to export the 'Steel_Lifetime_9Countries.xlsx' as an xls file. However, I wanted to signal the issue in case it has other repercussions on ODYM.

Best regards - and many thanks for publishing and maintaining this repo!
```
--------------------------------------------------------------------------
XLRDError                                 Traceback (most recent call last)
~/730843896.py in <module>
----> 1 LifetimeFile  = xlrd.open_workbook(os.path.join(DataPath, 'Steel_Lifetime_9Countries.xlsx'))
      2 Datasheet = LifetimeFile.sheet_by_name('Average_Lifetime')
      3 
      4 Lifetimes = []
      5 

~\xlrd\__init__.py in open_workbook(filename, logfile, verbosity, use_mmap, file_contents, encoding_override, formatting_info, on_demand, ragged_rows, ignore_workbook_corruption)
    168     # files that xlrd can parse don't start with the expected signature.
    169     if file_format and file_format != 'xls':
--> 170         raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
    171 
    172     bk = open_workbook_xls(

XLRDError: Excel xlsx file; not supported
```

**Comment by CBreton026** [comment]
Just as a follow-up, the issue does cause other problems in ODYM. For example, the function ReadParameterV2 adds the extension '.xlsx' to ParPath, which then causes the same XLRDError. A quick fix (on my local copy) was to simply change all files to .xls and change the function accordingly; however, I don't know if this is the best course of action for the program as a whole. 

```
def ReadParameterV2(ParPath, ThisPar, ThisParIx, IndexMatch, ThisParLayerSel, MasterClassification,
                    IndexTable, IndexTable_ClassificationNames, ScriptConfig, Mylog, ParseUncertainty):
    """
    This function reads a model parameter from the corresponding parameter file
    """
    Parfile   = xlrd.open_workbook(ParPath + '.xlsx')
    ParHeader = Parfile.sheet_by_name('Cover')
```

**Comment by stefanpauliuk** [comment]
Hi Charles!

thanks for checking! There is now a openpyxl-only version of ODYM and of RECC, and the parameter reading now happens with the new function
ReadParameterXLSX instead of f ReadParameterV2 
Please check and try!

**Comment by CBreton026** [comment]
Hi Stefan!

Thanks, I'll make sure to use the new function!
