### ISSUE TITLE
Parse Error: Tutorial 6, ParseModelControl

### ISSUE THREAD

**Issue by TUBSAiPTL** [IndEcol/ODYM#16]
Hi there,

I am trying to understand the MaTrace model, but I get an 'list index out of range' error for ParseModelControl in ODYM_Functions.py when running the Tutorial.

I did not change anything of the file, checked the Config file, but still could not figure it out since the referred cells are definitely defined.

I would be grateful for your help. I would like to use ODYM for a research project and would like to use the Tutorial as a basis.
Thank you very much and all the best.

![Bildschirmfoto 2022-02-09 um 14 48 43](https://user-images.githubusercontent.com/98967109/153214365-99408b66-0e62-409a-bf84-fb52e002b802.png)

**Comment by stefanpauliuk** [comment]
Hi @TUBSAiPTL, thanks for your message, I'll try to look into this during the coming days and let you know then. Cheers, Stefan

**Comment by stefanpauliuk** [comment]
Hi @TUBSAiPTL, I am sorry that this took me so long to look at. The reason why this tutorial does not work anymore is that we need to swith to a new library to read the xlsx files into Python.
I have now updated tutorial no. 6 to the new method, please download the latest version
https://github.com/IndEcol/ODYM/blob/master/docs/ODYM%20Example%20and%20Tutorial%20No.%206.%20MaTrace.ipynb 
and try again! All the best, Stefan
