### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by nheeren** [IndEcol/ODYM#7]
We got the license wrong. CC BY is intended to be used for content and not really for code: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

However, I am also not quite sure which would be the best. The most popular ones seem to be MIT, Apache or one if the GNU licenses. I wonder if we could ask Konstantin for advice?

**Comment by nheeren** [comment]
BTW - this is how github lets you choose a license: https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by nheeren** [comment]
https://choosealicense.com/
I would say MIT is closest to CC BY.

**Comment by stefanpauliuk** [comment]
Sounds good. Will change to MIT.

**Comment by nheeren** [comment]
👍
